/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ehospital.gui.login;

import ehospital.dao.DiseaseDao;
import ehospital.dao.DoctorDao;
import ehospital.dao.PatientDao;
import ehospital.dao.PaymentDao;
import ehospital.dao.ReceiptDao;
import ehospital.dao.RegistrationDao;
import ehospital.dao.RoomDao;
import ehospital.dao.WorkerDao;
import ehospital.dao.impl.DiseaseDaoImpl;
import ehospital.dao.impl.DoctorDaoImpl;
import ehospital.dao.impl.PatientDaoImpl;
import ehospital.dao.impl.PaymentDaoImpl;
import ehospital.dao.impl.ReceiptDaoImpl;
import ehospital.dao.impl.RegistrationDaoImpl;
import ehospital.dao.impl.RoomDaoImpl;
import ehospital.dao.impl.WorkerDaoImpl;
import ehospital.gui.main.MainFrame;
import ehospital.model.Doctor;
import ehospital.model.Patient;
import ehospital.model.Worker;
import ehospital.service.DiseaseService;
import ehospital.service.DoctorService;
import ehospital.service.PatientService;
import ehospital.service.PaymentService;
import ehospital.service.ReceiptService;
import ehospital.service.RegistrationService;
import ehospital.service.RoomService;
import ehospital.service.WorkerService;
import ehospital.service.impl.DiseaseServiceImpl;
import ehospital.service.impl.DoctorServiceImpl;
import ehospital.service.impl.PatientServiceImpl;
import ehospital.service.impl.PaymentServiceImpl;
import ehospital.service.impl.ReceiptServiceImpl;
import ehospital.service.impl.RegistrationServiceImpl;
import ehospital.service.impl.RoomServiceImpl;
import ehospital.service.impl.WorkerServiceImpl;
import java.util.List;
import javax.swing.ButtonGroup;

/**
 *
 * @author Qadirov Murad
 */
public class LoginFrame extends javax.swing.JFrame {

    ButtonGroup buttonGroup;
    PatientDao patientDao = new PatientDaoImpl();
    PatientService patientService = new PatientServiceImpl(patientDao);
    DoctorDao doctorDao = new DoctorDaoImpl();
    DoctorService doctorService = new DoctorServiceImpl(doctorDao);
    RegistrationDao registrationDao = new RegistrationDaoImpl();
    RegistrationService registrationService = new RegistrationServiceImpl(registrationDao);
    PaymentDao paymentDao = new PaymentDaoImpl();
    PaymentService paymentService = new PaymentServiceImpl(paymentDao);
    ReceiptDao receiptDao = new ReceiptDaoImpl();
    ReceiptService receiptService = new ReceiptServiceImpl(receiptDao);
    DiseaseDao diseaseDao = new DiseaseDaoImpl();
    DiseaseService diseaseService = new DiseaseServiceImpl(diseaseDao);
    RoomDao roomDao = new RoomDaoImpl();
    RoomService roomService = new RoomServiceImpl(roomDao);
    WorkerDao workerDao = new WorkerDaoImpl();
    WorkerService workerService = new WorkerServiceImpl(workerDao);

    public LoginFrame() {
        initComponents();
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdBtnPatient);
        buttonGroup.add(rdBtnWorker);
        buttonGroup.add(rdBtnDoctor);
        rdBtnPatient.setActionCommand("patient");
        rdBtnDoctor.setActionCommand("doctor");
        rdBtnWorker.setActionCommand("worker");
        rdBtnPatient.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        rdBtnPatient = new javax.swing.JRadioButton();
        rdBtnDoctor = new javax.swing.JRadioButton();
        rdBtnWorker = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        btnResett = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        lblFoot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setSize(new java.awt.Dimension(1020, 709));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblUserName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblUserName.setText("User Name:");

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPassword.setText("Password:");

        pswPassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        txtLogin.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        rdBtnPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rdBtnPatient.setText("Patient");

        rdBtnDoctor.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rdBtnDoctor.setText("Doctor");

        rdBtnWorker.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rdBtnWorker.setText("Worker");

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnResett.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnResett.setText("RESET");
        btnResett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResettActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(btnResett)
                .addGap(67, 67, 67)
                .addComponent(btnLogin)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(rdBtnPatient)
                .addGap(33, 33, 33)
                .addComponent(rdBtnDoctor)
                .addGap(30, 30, 30)
                .addComponent(rdBtnWorker)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pswPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(txtLogin))
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnDoctor)
                    .addComponent(rdBtnWorker)
                    .addComponent(rdBtnPatient))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnResett))
                .addGap(26, 26, 26))
        );

        lblHead.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblHead.setText("Hospital Management System");

        lblFoot.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblFoot.setText("Copyright @QadirovMurad 2002");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHead)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblFoot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76)
                .addComponent(lblFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String userType = null;
            String login = txtLogin.getText();
            String password = String.valueOf(pswPassword.getPassword());
            userType = buttonGroup.getSelection().getActionCommand();
            if (login.equals("") || password.equals("")) {
                lblInfo.setText("Please first fill!");
                return;
            }
            switch (userType) {
                case "patient":
                    List<Patient> patientList = patientService.getLoginedPatientList();
                    for (Patient patient : patientList) {
                        if (patient.getLogin().equals(login) && patient.getPassword().equals(password)) {
                            MainFrame mainFrame = new MainFrame(patientService, doctorService, registrationService, paymentService, receiptService, diseaseService, roomService,userType);
                            mainFrame.setVisible(true);
                            
                            this.dispose();
                            return;
                        }
                        lblInfo.setText("Wrong Login or Password!");
                    }
                    break;
                case "doctor":
                    List<Doctor> doctorList = doctorService.getLoginedDoctorList();
                    for (Doctor doctor : doctorList) {
                        if (doctor.getLogin().equals(login) && doctor.getPassword().equals(password)) {
                            MainFrame mainFrame = new MainFrame(patientService, doctorService, registrationService, paymentService, receiptService, diseaseService, roomService,userType);
                            mainFrame.setVisible(true);
                            this.dispose();
                            return;
                        }
                        lblInfo.setText("Wrong Login or Password!");
                    }
                    break;

                case "worker":
                    List<Worker> workerList = workerService.getLoginedDoctorList();
                    for (Worker worker : workerList) {
                        if (worker.getLogin().equals(login) && worker.getPassword().equals(password)) {
                            MainFrame mainFrame = new MainFrame(patientService, doctorService, registrationService, paymentService, receiptService, diseaseService, roomService,userType);
                            mainFrame.setVisible(true);
                            this.dispose();
                            return;
                        }
                        lblInfo.setText("Wrong Login or Password!");
                    }
                    break;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResettActionPerformed
        txtLogin.setText("");
        pswPassword.setText("");
        lblInfo.setText("");
        rdBtnPatient.setSelected(true);
    }//GEN-LAST:event_btnResettActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        
    }//GEN-LAST:event_txtLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnResett;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JRadioButton rdBtnDoctor;
    private javax.swing.JRadioButton rdBtnPatient;
    private javax.swing.JRadioButton rdBtnWorker;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
