/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ehospital.gui.edit;

import ehospital.model.Disease;
import ehospital.model.Doctor;
import ehospital.model.Patient;
import ehospital.model.Payment;
import ehospital.model.Registration;
import ehospital.model.Room;
import ehospital.service.DiseaseService;
import ehospital.service.DoctorService;
import ehospital.service.PatientService;
import ehospital.service.RegistrationService;
import ehospital.service.RoomService;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class EditRegistrationFrame extends javax.swing.JFrame {
    
    RegistrationService registrationService;
    PatientService patientService;
    DoctorService doctorService;
    DiseaseService diseaseService;
    RoomService roomService;
    private Long selectedRow;
    Registration registration;
    
    public EditRegistrationFrame(RegistrationService registrationService, PatientService patientService, DoctorService doctorService, DiseaseService diseaseService, RoomService roomService, Long selectedRow) {
        try {
            this.registrationService = registrationService;
            this.patientService = patientService;
            this.doctorService = doctorService;
            this.diseaseService = diseaseService;
            this.roomService = roomService;
            this.selectedRow = selectedRow;
            initComponents();
            fillPatientCmb();
            fillDoctorCmb();
            fillDiseaseCmb();
            fillRoomCmb();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPatient = new javax.swing.JComboBox<>();
        cmbDoctor = new javax.swing.JComboBox<>();
        cmbDisease = new javax.swing.JComboBox<>();
        cmbRoom = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblRegistration = new javax.swing.JLabel();
        lblRegisterIcn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbPatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Patient" }));
        cmbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientActionPerformed(evt);
            }
        });

        cmbDoctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor" }));

        cmbDisease.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Disease" }));
        cmbDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiseaseActionPerformed(evt);
            }
        });

        cmbRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room" }));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblRegistration.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblRegistration.setForeground(java.awt.Color.blue);
        lblRegistration.setText("Registration");

        lblRegisterIcn.setAutoscrolls(true);
        lblRegisterIcn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblRegisterIcn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDisease, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterIcn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cmbDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cmbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ImageIcon imageIcon = new ImageIcon("C:\\Users\\hp\\Desktop\\Java\\iconsEhospital\\rgstricon.png"); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back}
    lblRegisterIcn.setIcon(imageIcon);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientActionPerformed

    }//GEN-LAST:event_cmbPatientActionPerformed

    private void cmbDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiseaseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Registration registration = new Registration();
            registration.setId(selectedRow);
            registration.setPatient((Patient) cmbPatient.getSelectedItem());
            registration.setDoctor((Doctor) cmbDoctor.getSelectedItem());
            registration.setDisease((Disease) cmbDisease.getSelectedItem());
            registration.setRoom((Room) cmbRoom.getSelectedItem());
            registrationService.updateRegistration(registration);
            JOptionPane.showMessageDialog(null, "Registration Successfully updated !!!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cmbPatient.setSelectedItem("Select Patient");
        cmbDoctor.setSelectedItem("Select Doctor");
        cmbDisease.setSelectedItem("Select Disease");
        cmbRoom.setSelectedItem("Select Room");
    }//GEN-LAST:event_btnResetActionPerformed
    
    private void fillPatientCmb() {
        try {
            List<Patient> patients = patientService.getPatientList();
            DefaultComboBoxModel patientCombo = (DefaultComboBoxModel) cmbPatient.getModel();
            registration = registrationService.getRegistrationById(selectedRow);
            
            for (Patient patient : patients) {
                patientCombo.addElement(patient);
            }
            Patient patient = patientService.getPatientbyId(registration.getPatient().getId());
            patientCombo.setSelectedItem(patient);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void fillDoctorCmb() {
        try {
            List<Doctor> doctors = doctorService.getDoctorList();
            registration = registrationService.getRegistrationById(selectedRow);
            DefaultComboBoxModel doctorCombo = (DefaultComboBoxModel) cmbDoctor.getModel();
            for (Doctor doctor : doctors) {
                
                doctorCombo.addElement(doctor);
            }
            Doctor doctor = doctorService.getDoctorbyId(registration.getDoctor().getId());
            doctorCombo.setSelectedItem(doctor);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void fillDiseaseCmb() {
        try {
            List<Disease> diseases = diseaseService.getDiseaseList();
            registration = registrationService.getRegistrationById(selectedRow);
            DefaultComboBoxModel diseaseCombo = (DefaultComboBoxModel) cmbDisease.getModel();
            for (Disease disease : diseases) {
                diseaseCombo.addElement(disease);
            }
            Disease disease = diseaseService.getDiseaseById(registration.getDisease().getID());
            diseaseCombo.setSelectedItem(disease);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void fillRoomCmb() {
        try {
            List<Room> rooms = roomService.getRoomList();
            registration = registrationService.getRegistrationById(selectedRow);
            DefaultComboBoxModel roomCombo = (DefaultComboBoxModel) cmbRoom.getModel();
            for (Room room : rooms) {
                roomCombo.addElement(room);
            }
            Room room = roomService.getRoomById(registration.getRoom().getId());
            roomCombo.setSelectedItem(room);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDisease;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JComboBox<String> cmbRoom;
    private javax.swing.JLabel lblRegisterIcn;
    private javax.swing.JLabel lblRegistration;
    // End of variables declaration//GEN-END:variables
}
